services:

  # Database service
  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ../DB/dbCreate.sql:/docker-entrypoint-initdb.d/01_dbCreate.sql
      - ../DB/populate.sql:/docker-entrypoint-initdb.d/02_populate.sql
    networks:
      - backend-network

  
  # Frontend services (ajusta el contexto si tienes la carpeta Frontend)
  frontend1:
    build:
      context: ../Frontend
      dockerfile: Dockerfile
    networks:
      - frontend-network

  frontend2:
    build:
      context: ../Frontend
      dockerfile: Dockerfile
    networks:
      - frontend-network

  frontend3:
    build:
      context: ../Frontend
      dockerfile: Dockerfile
    networks:
      - frontend-network

  # Nginx para balanceo de frontend
  nginx-frontend:
    image: nginx:latest
    ports:
      - "8070:80"
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network

  # Backend services
  backend1:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - db
    networks:
      - backend-network

  backend2:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - db
    networks:
      - backend-network

  backend3:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - db
    networks:
      - backend-network

  # Nginx para balanceo de backend
  nginx-backend:
    image: nginx:latest
    ports:
      - "8090:80"
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network:

volumes:
  db_data: